# Generated by Django 5.2 on 2026-07-04 22:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0004_cenikpolozka_aktivni_cenikpolozka_delka_minut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatniSvatky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(unique=True, verbose_name='datum')),
                ('nazev', models.CharField(max_length=100, verbose_name='název')),
            ],
            options={
                'verbose_name': 'státní svátek',
                'verbose_name_plural': 'státní svátky',
                'ordering': ['datum'],
            },
        ),
        migrations.CreateModel(
            name='OpakovanaRezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_tydnu', models.PositiveIntegerField(default=6, verbose_name='interval (týdny)')),
                ('dalsi_termin', models.DateTimeField(verbose_name='další termín')),
                ('aktivni', models.BooleanField(default=True)),
                ('poznamka', models.TextField(blank=True)),
                ('sluzby_ids', models.JSONField(default=list, verbose_name='ID služeb')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opakovane', to='salons.salon')),
            ],
            options={
                'verbose_name': 'opakovaná rezervace',
                'verbose_name_plural': 'opakované rezervace',
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(verbose_name='začátek')),
                ('konec', models.DateTimeField(verbose_name='konec')),
                ('stav', models.CharField(choices=[('ceka', 'Čeká na potvrzení'), ('potvrzeno', 'Potvrzeno'), ('zakaznik_storno', 'Zákazník zrušil'), ('salon_storno', 'Salon zrušil'), ('dokonceno', 'Dokončeno'), ('no_show', 'Zákazník se nedostavil')], default='ceka', max_length=20, verbose_name='stav')),
                ('poznamka_zakaznika', models.TextField(blank=True, verbose_name='poznámka zákazníka')),
                ('poznamka_interni', models.TextField(blank=True, verbose_name='interní poznámka')),
                ('typ_vytvoreni', models.CharField(choices=[('online', 'Online'), ('telefon', 'Telefonicky'), ('osobne', 'Osobně'), ('zamestnanec', 'Zaměstnancem')], default='online', max_length=20, verbose_name='typ vytvoření')),
                ('cancel_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('skutecna_delka_minut', models.PositiveIntegerField(blank=True, null=True)),
                ('dokonceno_at', models.DateTimeField(blank=True, null=True)),
                ('pripominka_odeslana', models.JSONField(default=list)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('aktualizovano', models.DateTimeField(auto_now=True)),
                ('jmeno_host', models.CharField(blank=True, max_length=100, verbose_name='jméno (host)')),
                ('email_host', models.EmailField(blank=True, max_length=254, verbose_name='e-mail (host)')),
                ('opakovana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezervace.opakovanarezervace')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rezervace', to='salons.salon')),
            ],
            options={
                'verbose_name': 'rezervace',
                'verbose_name_plural': 'rezervace',
                'ordering': ['zacatek'],
            },
        ),
        migrations.CreateModel(
            name='RezervaceHistorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdo', models.CharField(max_length=100, verbose_name='kdo')),
                ('kdy', models.DateTimeField(auto_now_add=True)),
                ('popis', models.TextField(verbose_name='popis změny')),
                ('data_pred', models.JSONField(blank=True, null=True)),
                ('data_po', models.JSONField(blank=True, null=True)),
                ('rezervace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historie', to='rezervace.rezervace')),
            ],
            options={
                'verbose_name': 'historie rezervace',
                'verbose_name_plural': 'historie rezervací',
                'ordering': ['-kdy'],
            },
        ),
        migrations.CreateModel(
            name='RezervaceSluzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poradi', models.PositiveIntegerField(default=0)),
                ('rezervace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozky', to='rezervace.rezervace')),
                ('sluzba', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='salons.cenikpolozka')),
            ],
            options={
                'verbose_name': 'služba rezervace',
                'verbose_name_plural': 'služby rezervace',
                'ordering': ['poradi'],
            },
        ),
        migrations.CreateModel(
            name='RezervacniNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_minut', models.PositiveIntegerField(choices=[(5, '5 minut'), (10, '10 minut'), (15, '15 minut'), (30, '30 minut')], default=15, verbose_name='interval rezervací')),
                ('min_predstih_hodin', models.PositiveIntegerField(default=2, verbose_name='min. předstih (h)')),
                ('max_predstih_mesicu', models.PositiveIntegerField(default=3, verbose_name='max. předstih (měsíce)')),
                ('pripominka_hodin', models.JSONField(default=list, verbose_name='připomínky (h)')),
                ('storno_do_hodin', models.PositiveIntegerField(blank=True, null=True, verbose_name='storno do (h)')),
                ('platba_qr_text', models.TextField(blank=True, verbose_name='QR / platební instrukce')),
                ('auto_potvrzeni', models.BooleanField(default=True, verbose_name='automatické potvrzení')),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rezervacni_nastaveni', to='salons.salon')),
            ],
            options={
                'verbose_name': 'nastavení rezervací',
                'verbose_name_plural': 'nastavení rezervací',
            },
        ),
        migrations.CreateModel(
            name='SalonVyjimka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField(verbose_name='od')),
                ('datum_do', models.DateField(verbose_name='do')),
                ('duvod', models.CharField(blank=True, max_length=200, verbose_name='důvod')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vyjimky', to='salons.salon')),
            ],
            options={
                'verbose_name': 'mimořádné uzavření',
                'verbose_name_plural': 'mimořádná uzavření',
                'ordering': ['datum_od'],
            },
        ),
        migrations.CreateModel(
            name='Zakaznik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=100, verbose_name='přezdívka')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('gdpr_souhlas', models.BooleanField(default=False, verbose_name='GDPR souhlas')),
                ('gdpr_datum', models.DateTimeField(blank=True, null=True, verbose_name='GDPR datum')),
                ('marketing_souhlas', models.BooleanField(default=False, verbose_name='marketing souhlas')),
                ('blokovan', models.BooleanField(default=False, verbose_name='blokován')),
                ('no_show_pocet', models.PositiveIntegerField(default=0, verbose_name='počet no-show')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakaznici', to='salons.salon')),
            ],
            options={
                'verbose_name': 'zákazník',
                'verbose_name_plural': 'zákazníci',
                'ordering': ['-vytvoreno'],
                'unique_together': {('salon', 'email')},
            },
        ),
        migrations.AddField(
            model_name='rezervace',
            name='zakaznik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezervace.zakaznik'),
        ),
        migrations.AddField(
            model_name='opakovanarezervace',
            name='zakaznik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rezervace.zakaznik'),
        ),
        migrations.CreateModel(
            name='ZakaznikSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('expirace', models.DateTimeField()),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessiony', to='rezervace.zakaznik')),
            ],
            options={
                'verbose_name': 'session zákazníka',
                'verbose_name_plural': 'sessiony zákazníků',
            },
        ),
        migrations.CreateModel(
            name='Zamestnanec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='jméno')),
                ('specializace', models.CharField(blank=True, max_length=200, verbose_name='specializace')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('poradi', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zamestnanci', to='salons.salon')),
            ],
            options={
                'verbose_name': 'zaměstnanec',
                'verbose_name_plural': 'zaměstnanci',
                'ordering': ['poradi', 'id'],
            },
        ),
        migrations.AddField(
            model_name='rezervace',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, help_text='Prázdné = kdokoliv', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezervace.zamestnanec'),
        ),
        migrations.AddField(
            model_name='opakovanarezervace',
            name='zamestnanec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rezervace.zamestnanec'),
        ),
        migrations.CreateModel(
            name='BlokaceCasu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(verbose_name='začátek')),
                ('konec', models.DateTimeField(verbose_name='konec')),
                ('popis', models.CharField(blank=True, max_length=200, verbose_name='popis')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blokace', to='salons.salon')),
                ('zamestnanec', models.ForeignKey(blank=True, help_text='Prázdné = celý salon', null=True, on_delete=django.db.models.deletion.CASCADE, to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'blokace času',
                'verbose_name_plural': 'blokace času',
                'ordering': ['zacatek'],
            },
        ),
        migrations.CreateModel(
            name='ZamestnanecAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_od', models.DateField(verbose_name='od')),
                ('datum_do', models.DateField(verbose_name='do')),
                ('typ', models.CharField(choices=[('volno', 'Volno'), ('dovolena', 'Dovolená'), ('nemoc', 'Nemoc')], default='dovolena', max_length=20, verbose_name='typ')),
                ('poznamka', models.CharField(blank=True, max_length=200, verbose_name='poznámka')),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'absence zaměstnance',
                'verbose_name_plural': 'absence zaměstnanců',
                'ordering': ['datum_od'],
            },
        ),
        migrations.CreateModel(
            name='ZamestnanecRozvrh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(choices=[(0, 'Pondělí'), (1, 'Úterý'), (2, 'Středa'), (3, 'Čtvrtek'), (4, 'Pátek'), (5, 'Sobota'), (6, 'Neděle')], verbose_name='den')),
                ('od', models.TimeField(blank=True, null=True, verbose_name='od')),
                ('do', models.TimeField(blank=True, null=True, verbose_name='do')),
                ('volno', models.BooleanField(default=False, verbose_name='volno')),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rozvrh', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'rozvrh zaměstnance',
                'verbose_name_plural': 'rozvrhy zaměstnanců',
                'ordering': ['den'],
                'unique_together': {('zamestnanec', 'den')},
            },
        ),
    ]
