# Generated by Django 5.2 on 2026-07-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='email_jmeno_odesilatele',
            field=models.CharField(blank=True, help_text='Zobrazí se v poli Od: (např. Salon Elegance).', max_length=100, verbose_name='jméno odesílatele'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='email_odesilatel',
            field=models.EmailField(blank=True, help_text='Prázdné = použije se e-mail salonu z webu.', max_length=254, verbose_name='e-mail odesílatele'),
        ),
    ]
