# Generated by Django 5.2 on 2026-07-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0002_rezervacninastaveni_email_jmeno_odesilatele_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='smtp_host',
            field=models.CharField(blank=True, default='smtp.forpsi.com', max_length=200, verbose_name='SMTP server'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=200, verbose_name='SMTP heslo'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='smtp_port',
            field=models.PositiveIntegerField(default=465, verbose_name='SMTP port'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='smtp_use_ssl',
            field=models.BooleanField(default=True, verbose_name='SMTP SSL'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='smtp_user',
            field=models.EmailField(blank=True, max_length=254, verbose_name='SMTP přihlášení'),
        ),
    ]
