# Generated by Django 5.2 on 2026-07-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0003_rezervacninastaveni_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='web_rezervace_url',
            field=models.URLField(blank=True, help_text='Odkazy v e-mailech. Např. https://vase-domena.cz/rezervace.html', verbose_name='URL stránky rezervací'),
        ),
    ]
