# Generated by Django 5.2 on 2026-07-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0004_rezervacninastaveni_web_rezervace_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='zakaznik',
            name='password_hash',
            field=models.CharField(blank=True, max_length=128, verbose_name='heslo (hash)'),
        ),
    ]
