# Generated by Django 5.2 on 2026-07-04 23:52

import uuid

from django.db import migrations, models


def preved_stare_pripominky(apps, schema_editor):
    RezervacniNastaveni = apps.get_model('rezervace', 'RezervacniNastaveni')
    Rezervace = apps.get_model('rezervace', 'Rezervace')

    for nast in RezervacniNastaveni.objects.all():
        stare = getattr(nast, 'pripominka_hodin', None) or []
        if stare:
            notifikace = []
            for h in stare[:3]:
                try:
                    h = int(h)
                except (TypeError, ValueError):
                    continue
                notifikace.append({
                    'id': str(uuid.uuid4()),
                    'offset': f'+{h}',
                    'aktivni': True,
                    'predmet': 'Připomínka rezervace – {{ salon.name }}',
                    'text': '',
                })
            nast.notifikace = notifikace
        elif not nast.notifikace:
            nast.notifikace = [{
                'id': str(uuid.uuid4()),
                'offset': '+24',
                'aktivni': True,
                'predmet': 'Připomínka rezervace – {{ salon.name }}',
                'text': '',
            }]
        nast.save(update_fields=['notifikace'])

    for rez in Rezervace.objects.all():
        stare = getattr(rez, 'pripominka_odeslana', None) or []
        if stare and not rez.notifikace_odeslane:
            rez.notifikace_odeslane = [str(x) for x in stare]
            rez.save(update_fields=['notifikace_odeslane'])


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0005_zakaznik_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervace',
            name='notifikace_odeslane',
            field=models.JSONField(default=list, verbose_name='odeslané notifikace (id)'),
        ),
        migrations.AddField(
            model_name='rezervacninastaveni',
            name='notifikace',
            field=models.JSONField(blank=True, default=list, help_text='Až 3 notifikace: offset +24 / -2, předmět, text, aktivní.', verbose_name='e-mailové notifikace'),
        ),
        migrations.RunPython(preved_stare_pripominky, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='rezervace',
            name='pripominka_odeslana',
        ),
        migrations.RemoveField(
            model_name='rezervacninastaveni',
            name='pripominka_hodin',
        ),
    ]
