# Generated by Django 5.2 on 2026-07-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0006_notifikace_nastaveni'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamestnanec',
            name='fotka',
            field=models.URLField(blank=True, verbose_name='fotka'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='popis',
            field=models.TextField(blank=True, verbose_name='popis na webu'),
        ),
        migrations.AddField(
            model_name='zamestnanec',
            name='zobrazit_na_webu',
            field=models.BooleanField(default=True, verbose_name='zobrazit na webu'),
        ),
    ]
