# Generated by Django 5.2 on 2026-07-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0020_gdpr_compliance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='souhlasgdpr',
            options={'ordering': ['-vytvoreno'], 'verbose_name': 'potvrzení seznámení se zásadami', 'verbose_name_plural': 'potvrzení seznámení se zásadami'},
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='gdpr_datum',
            field=models.DateTimeField(blank=True, null=True, verbose_name='datum potvrzení zásad'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='gdpr_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP při potvrzení zásad'),
        ),
        migrations.AlterField(
            model_name='zakaznik',
            name='gdpr_souhlas',
            field=models.BooleanField(default=False, verbose_name='potvrzení seznámení se zásadami'),
        ),
    ]
