# Generated by Django 5.2 on 2026-07-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0021_gdpr_terminologie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezervacninastaveni',
            name='uchovavani_mesicu',
        ),
    ]
