# Generated by Django 5.2 on 2026-07-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0023_majitel_neprovadi_sluzby'),
        ('salons', '0004_cenikpolozka_aktivni_cenikpolozka_delka_minut_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='noshowzaznam',
            index=models.Index(fields=['salon', 'email'], name='noshow_salon_email_idx'),
        ),
        migrations.AddIndex(
            model_name='rezervace',
            index=models.Index(fields=['salon', 'zacatek'], name='rezervace_salon_zacatek_idx'),
        ),
        migrations.AddIndex(
            model_name='rezervace',
            index=models.Index(fields=['salon', 'stav'], name='rezervace_salon_stav_idx'),
        ),
    ]
