# Generated by Django 5.2 on 2026-07-28 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervace', '0030_absence_stav'),
        ('salons', '0008_cenikpolozka_rizikovy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZamestnanecSluzba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sluzba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prirazeni_personalu', to='salons.cenikpolozka')),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prirazene_sluzby', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'přiřazení služby personálu',
                'verbose_name_plural': 'přiřazení služeb personálu',
                'unique_together': {('zamestnanec', 'sluzba')},
            },
        ),
    ]
