# Generated by Django 5.2 on 2026-08-26 13:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('sort', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='modernik-flow', max_length=40)),
                ('external_service_id', models.CharField(max_length=80)),
                ('name_snapshot', models.CharField(max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name_snapshot', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Zapíná se'), ('active', 'Aktivní'), ('inactive', 'Vypnuto'), ('error', 'Chyba')], db_index=True, default='pending', max_length=20)),
                ('provisioning_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('barcode', models.CharField(blank=True, max_length=80)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('critical_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('last_purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.category')),
                ('primary_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('service_mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='sklad.servicemapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant'),
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Provozovna', max_length=80)),
                ('is_default', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('staff_external_id', models.CharField(max_length=40)),
                ('staff_name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, max_length=30)),
                ('je_majitel', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='sklad.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='servicemapping',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant'),
        ),
        migrations.CreateModel(
            name='InboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(default='modernik-flow', max_length=40)),
                ('event_type', models.CharField(max_length=80)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='received', max_length=20)),
                ('reject_reason', models.CharField(blank=True, max_length=80)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(default='system', max_length=80)),
                ('action', models.CharField(max_length=80)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('status', models.CharField(db_index=True, default='open', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='sklad.material')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid', models.CharField(default='tenant', max_length=40)),
                ('secret', models.CharField(max_length=128)),
                ('key_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='sklad.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='TenantSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='modernik-flow', max_length=40)),
                ('external_tenant_id', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='sklad.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('type', models.CharField(choices=[('auto_consume', 'Automatická spotřeba'), ('consume_confirm', 'Potvrzená spotřeba'), ('manual_adjust', 'Ruční korekce'), ('inventory', 'Inventura'), ('purchase_receipt', 'Příjem'), ('reverse', 'Storno pohybu')], max_length=30)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(blank=True, max_length=40)),
                ('external_event_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('reservation_ref', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_by_type', models.CharField(default='system', max_length=20)),
                ('created_by_user_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.stocklocation')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='sklad.material')),
                ('service_mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.servicemapping')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_buy', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(db_index=True, default='open', max_length=20)),
                ('origin', models.CharField(default='auto_min', max_length=20)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping', to='sklad.material')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sklad.supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.unit')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.material')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sklad.recipe')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklad.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sklad.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='servicemapping',
            constraint=models.UniqueConstraint(fields=('tenant', 'source', 'external_service_id'), name='unique_tenant_service_mapping'),
        ),
        migrations.AddConstraint(
            model_name='tenantsource',
            constraint=models.UniqueConstraint(fields=('source', 'external_tenant_id'), name='unique_source_external_tenant'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('origin', 'auto_min'), ('status', 'open')), fields=('tenant', 'material'), name='unique_open_auto_shopping'),
        ),
    ]
