# Generated by Django 5.2 on 2026-07-22 23:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rezervace', '0024_rezervace_salon_indexes'),
        ('salons', '0005_cenikpolozka_obrazek'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('password_hash', models.CharField(max_length=128, verbose_name='heslo (hash)')),
                ('visible_overview', models.BooleanField(default=False, verbose_name='Visible Overview')),
                ('aktivni', models.BooleanField(default=True, verbose_name='aktivní')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_users', to='salons.salon')),
                ('zamestnanec', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_ucet', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'FLOW účet',
                'verbose_name_plural': 'FLOW účty',
            },
        ),
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('expirace', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessiony', to='flow.flowuser')),
            ],
            options={
                'verbose_name': 'FLOW session',
                'verbose_name_plural': 'FLOW sessiony',
            },
        ),
        migrations.AddConstraint(
            model_name='flowuser',
            constraint=models.UniqueConstraint(fields=('email',), name='flow_user_email_unique'),
        ),
    ]
