# Generated by Django 5.2 on 2026-08-04 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_flow_mail_odeslano'),
        ('salons', '0008_cenikpolozka_rizikovy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('jmeno', models.CharField(blank=True, default='', max_length=120, verbose_name='jméno')),
                ('telefon', models.CharField(blank=True, default='', max_length=40, verbose_name='telefon')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='poznámka o zákazníkovi')),
                ('stav', models.CharField(choices=[('ceka_na_potvrzeni', 'Čeká na potvrzení'), ('aktivni', 'Aktivní')], db_index=True, default='ceka_na_potvrzeni', max_length=32)),
                ('confirm_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('confirm_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirm_token_used_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_cards', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_cards_vytvorene', to='flow.flowuser')),
            ],
            options={
                'verbose_name': 'Zákaznická karta',
                'verbose_name_plural': 'Zákaznické karty',
            },
        ),
        migrations.CreateModel(
            name='CustomerVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='datum')),
                ('text', models.TextField(verbose_name='záznam')),
                ('autor_jmeno', models.CharField(blank=True, default='', max_length=120, verbose_name='autor (jméno)')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_visits', to='flow.flowuser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='flow.customercard')),
            ],
            options={
                'verbose_name': 'Zápis návštěvy',
                'verbose_name_plural': 'Zápisy návštěv',
                'ordering': ['-datum', '-vytvoreno'],
            },
        ),
        migrations.AddIndex(
            model_name='customercard',
            index=models.Index(fields=['salon', 'stav'], name='flow_cc_salon_stav_idx'),
        ),
        migrations.AddIndex(
            model_name='customercard',
            index=models.Index(fields=['salon', 'email'], name='flow_cc_salon_email_idx'),
        ),
        migrations.AddConstraint(
            model_name='customercard',
            constraint=models.UniqueConstraint(fields=('salon', 'email'), name='flow_customer_card_salon_email_uniq'),
        ),
    ]
