from archivnik.presets._fields import (
    PLET_PODTON,
    PLET_TYP,
    VLASY_DELKA,
    VLASY_HUSTOTA,
    VLASY_JEMNOST,
    VLASY_STAV,
    VLASY_TYP,
    VOUSY_HUSTOTA,
    f,
    t,
)

BEAUTY = {
    'kod': 'beauty',
    'nazev': 'Kadeřnický & beauty salon',
    'typy': [
        t('Vlasy', [
            f('Typ vlasů', 'vyber', VLASY_TYP),
            f('Jemnost vlasu', 'vyber', VLASY_JEMNOST),
            f('Hustota', 'vyber', VLASY_HUSTOTA),
            f('Délka', 'vyber', VLASY_DELKA),
            f('Přirozená barva', 'text'),
            f('Aktuální barva', 'text'),
            f('Šediny', 'text'),
            f('Stav vlasů', 'vyber', VLASY_STAV),
            f('Poslední používaná receptura', 'dlouhy_text'),
            f('Preferovaná značka', 'text'),
            f('Citlivost / alergie', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Vousy', [
            f('Typ vousů', 'text'),
            f('Hustota', 'vyber', VOUSY_HUSTOTA),
            f('Délka', 'text'),
            f('Preferovaný tvar', 'text'),
            f('Citlivost pokožky', 'dlouhy_text'),
            f('Preferované produkty', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Pleť / obličej', [
            f('Typ pleti', 'vyber', PLET_TYP),
            f('Podtón', 'vyber', PLET_PODTON),
            f('Odstín make-upu', 'text'),
            f('Citlivost', 'ano_ne'),
            f('Alergie', 'dlouhy_text'),
            f('Problematické oblasti', 'dlouhy_text'),
            f('Preferované produkty', 'dlouhy_text'),
            f('Nevhodné produkty', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Obočí', [
            f('Přirozená barva', 'text'),
            f('Preferovaný odstín', 'text'),
            f('Preferovaný tvar', 'text'),
            f('Citlivost pokožky', 'ano_ne'),
            f('Používaná barva / produkt', 'text'),
            f('Alergie', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Řasy', [
            f('Přirozené řasy', 'text'),
            f('Preferovaný efekt', 'text'),
            f('Preferovaná délka', 'text'),
            f('Preferované zakřivení', 'text'),
            f('Citlivé oči', 'ano_ne'),
            f('Alergie', 'dlouhy_text'),
            f('Používané produkty', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Nehty rukou', [
            f('Typ přírodních nehtů', 'text'),
            f('Tvar', 'text'),
            f('Preferovaná délka', 'text'),
            f('Preferovaný tvar', 'text'),
            f('Preferované barvy', 'text'),
            f('Používaný materiál', 'text'),
            f('Citlivost / alergie', 'dlouhy_text'),
            f('Problematické nehty', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Nehty nohou', [
            f('Stav nehtů', 'text'),
            f('Preferovaný tvar', 'text'),
            f('Preferované barvy', 'text'),
            f('Používaný materiál', 'text'),
            f('Citlivost', 'dlouhy_text'),
            f('Problematické oblasti', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
    ],
}
