from archivnik.presets._fields import POHON, f, t

PNEU = {
    'kod': 'pneu',
    'nazev': 'Pneuservis',
    'typy': [
        t('Osobní vůz', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('Alternativní rozměr', 'text'),
            f('TPMS', 'ano_ne'),
            f('Typ pohonu', 'vyber', POHON),
            f('Aktuální km', 'cislo'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('SUV / 4×4', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('Alternativní rozměr', 'text'),
            f('TPMS', 'ano_ne'),
            f('Aktuální km', 'cislo'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Dodávka', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('Zesílené / C pneumatiky', 'ano_ne'),
            f('TPMS', 'ano_ne'),
            f('Aktuální km', 'cislo'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Nákladní vůz', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Počet náprav', 'cislo'),
            f('Rozměr předních pneumatik', 'text'),
            f('Rozměr zadních pneumatik', 'text'),
            f('Další rozměry', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Motocykl', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Přední pneumatika', 'text'),
            f('Zadní pneumatika', 'text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Skútr', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('Rok výroby', 'cislo'),
            f('Přední pneumatika', 'text'),
            f('Zadní pneumatika', 'text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Čtyřkolka', [
            f('SPZ / identifikace', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Přední pneumatika', 'text'),
            f('Zadní pneumatika', 'text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Přívěsný vozík', [
            f('SPZ', 'text'),
            f('Výrobce', 'text'),
            f('Model', 'text'),
            f('VIN / výrobní číslo', 'text'),
            f('Rok výroby', 'cislo'),
            f('Počet náprav', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Obytný vůz', [
            f('SPZ', 'text'),
            f('Značka', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('TPMS', 'ano_ne'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Karavan', [
            f('SPZ', 'text'),
            f('Výrobce', 'text'),
            f('Model', 'text'),
            f('VIN', 'text'),
            f('Rok výroby', 'cislo'),
            f('Počet náprav', 'cislo'),
            f('Rozměr pneumatik', 'text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Traktor / zemědělský stroj', [
            f('SPZ / registrační značka', 'text'),
            f('Výrobce', 'text'),
            f('Model', 'text'),
            f('VIN / výrobní číslo', 'text'),
            f('Rok výroby', 'cislo'),
            f('Přední pneumatiky', 'text'),
            f('Zadní pneumatiky', 'text'),
            f('Další rozměry', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Pracovní stroj', [
            f('Identifikace / SPZ', 'text'),
            f('Výrobce', 'text'),
            f('Model', 'text'),
            f('Výrobní číslo', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměry pneumatik', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
        t('Jiné vozidlo', [
            f('SPZ / identifikace', 'text'),
            f('Výrobce / značka', 'text'),
            f('Model', 'text'),
            f('VIN / výrobní číslo', 'text'),
            f('Rok výroby', 'cislo'),
            f('Rozměry pneumatik', 'dlouhy_text'),
            f('Poznámka', 'dlouhy_text'),
        ]),
    ],
}
