from archivnik.presets._fields import POHLAVI, f, t

VET = {
    'kod': 'vet',
    'nazev': 'Veterinární ordinace',
    'typy': [
        t('Pes', [
            f('Plemeno', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva / zbarvení', 'text'),
            f('Číslo čipu', 'text'),
            f('Číslo pasu', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Kočka', [
            f('Plemeno', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva / zbarvení', 'text'),
            f('Číslo čipu', 'text'),
            f('Číslo pasu', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Králík', [
            f('Plemeno', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Číslo čipu', 'text'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Morče', [
            f('Plemeno', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Křeček', [
            f('Druh / plemeno', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Osmák degu', [
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Fretka', [
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Číslo čipu', 'text'),
            f('Číslo pasu', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Činčila', [
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Potkan', [
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva / varianta', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Myš', [
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva', 'text'),
            f('Hmotnost', 'cislo'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Pták / papoušek', [
            f('Druh', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození / vylíhnutí', 'datum'),
            f('Zbarvení', 'text'),
            f('Identifikační kroužek', 'text'),
            f('Číslo čipu', 'text'),
            f('Hmotnost', 'cislo'),
            f('Alergie / upozornění', 'dlouhy_text'),
        ]),
        t('Želva', [
            f('Druh', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Hmotnost', 'cislo'),
            f('Délka krunýře', 'cislo'),
            f('Číslo čipu', 'text'),
            f('Upozornění', 'dlouhy_text'),
        ]),
        t('Plaz', [
            f('Druh', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Zbarvení / morfa', 'text'),
            f('Hmotnost', 'cislo'),
            f('Délka', 'cislo'),
            f('Číslo čipu', 'text'),
            f('Upozornění', 'dlouhy_text'),
        ]),
        t('Jiné zvíře', [
            f('Druh', 'text'),
            f('Plemeno / varianta', 'text'),
            f('Pohlaví', 'vyber', POHLAVI),
            f('Datum narození', 'datum'),
            f('Barva / zbarvení', 'text'),
            f('Identifikační číslo', 'text'),
            f('Hmotnost', 'cislo'),
            f('Kastrace', 'ano_ne'),
            f('Upozornění', 'dlouhy_text'),
        ]),
    ],
}
