# Generated by Django 5.2 on 2026-07-16 00:54

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salons', '0004_cenikpolozka_aktivni_cenikpolozka_delka_minut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerNastaveni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domena', models.CharField(blank=True, max_length=253, verbose_name='vlastní doména')),
                ('stav', models.CharField(choices=[('active', 'ACTIVE'), ('blocked', 'BLOCKED')], db_index=True, default='active', max_length=20, verbose_name='stav služby')),
                ('tarif', models.CharField(blank=True, max_length=100, verbose_name='tarif')),
                ('fakturacni_email', models.EmailField(blank=True, max_length=254, verbose_name='fakturační e-mail')),
                ('variabilni_symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Variabilní symbol musí obsahovat 1 až 10 číslic.', regex='^\\d{1,10}$')], verbose_name='variabilní symbol')),
                ('periodicita', models.CharField(choices=[('monthly', 'Měsíčně'), ('yearly', 'Ročně')], default='monthly', max_length=20, verbose_name='periodicita')),
                ('castka', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='částka')),
                ('dalsi_splatnost', models.DateField(blank=True, db_index=True, null=True, verbose_name='další splatnost')),
                ('blokovan_od', models.DateTimeField(blank=True, null=True, verbose_name='blokován od')),
                ('duvod_blokace', models.CharField(blank=True, max_length=300, verbose_name='důvod blokace')),
                ('aktualizovano', models.DateTimeField(auto_now=True)),
                ('salon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_nastaveni', to='salons.salon')),
            ],
            options={
                'verbose_name': 'nastavení partnera',
                'verbose_name_plural': 'nastavení partnerů',
                'ordering': ['salon__name'],
            },
        ),
        migrations.CreateModel(
            name='TechnickaChyba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('cas', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metoda', models.CharField(blank=True, max_length=10)),
                ('cesta', models.CharField(max_length=500)),
                ('typ_chyby', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('vyreseno', models.BooleanField(db_index=True, default=False)),
                ('salon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technicke_chyby', to='salons.salon')),
            ],
            options={
                'verbose_name': 'technická chyba',
                'verbose_name_plural': 'technické chyby',
                'ordering': ['-cas'],
            },
        ),
        migrations.CreateModel(
            name='UpozorneniPlatby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splatnost', models.DateField()),
                ('prijemce', models.EmailField(max_length=254)),
                ('predmet', models.CharField(max_length=200)),
                ('uspesne', models.BooleanField(default=False)),
                ('chyba', models.CharField(blank=True, max_length=500)),
                ('odeslano', models.DateTimeField(auto_now_add=True)),
                ('odeslal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='odeslana_upozorneni_plateb', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upozorneni_plateb', to='salons.salon')),
            ],
            options={
                'verbose_name': 'upozornění platby',
                'verbose_name_plural': 'upozornění plateb',
                'ordering': ['-odeslano'],
            },
        ),
        migrations.CreateModel(
            name='PlatbaPartnera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splatnost', models.DateField(verbose_name='původní splatnost')),
                ('zaplaceno_dne', models.DateField(verbose_name='zaplaceno dne')),
                ('ocekavana_castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prijata_castka', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('variabilni_symbol', models.CharField(blank=True, max_length=10)),
                ('poznamka', models.CharField(blank=True, max_length=300)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('oznacil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oznacene_partnerske_platby', to=settings.AUTH_USER_MODEL)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerske_platby', to='salons.salon')),
            ],
            options={
                'verbose_name': 'platba partnera',
                'verbose_name_plural': 'platby partnerů',
                'ordering': ['-splatnost', '-id'],
                'constraints': [models.UniqueConstraint(fields=('salon', 'splatnost'), name='unique_partner_payment_due_date')],
            },
        ),
    ]
