# Generated by Django 5.2 on 2026-07-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_admin', '0002_create_existing_partner_settings'),
        ('salons', '0004_cenikpolozka_aktivni_cenikpolozka_delka_minut_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partnernastaveni',
            constraint=models.UniqueConstraint(condition=models.Q(('domena', ''), _negated=True), fields=('domena',), name='unique_nonempty_partner_domain'),
        ),
    ]
