# Generated by Django 5.2 on 2026-07-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_admin', '0003_partnernastaveni_unique_nonempty_partner_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='upozorneniplatby',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
