# Generated by Django 5.2 on 2026-08-28 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner_admin', '0013_odznac_ostre_partnery'),
        ('salons', '0008_cenikpolozka_rizikovy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFaktura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_faktury', models.CharField(max_length=30, unique=True, verbose_name='číslo faktury')),
                ('variabilni_symbol', models.CharField(blank=True, max_length=10, verbose_name='variabilní symbol')),
                ('popis', models.CharField(max_length=200, verbose_name='položka')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stav', models.CharField(choices=[('uhrazeno', 'Uhrazeno'), ('k_uhrade', 'K úhradě')], db_index=True, default='k_uhrade', max_length=20)),
                ('datum_vystaveni', models.DateField(db_index=True)),
                ('datum_splatnosti', models.DateField(blank=True, null=True)),
                ('datum_uhrady', models.DateField(blank=True, null=True)),
                ('faktura_pdf', models.FileField(blank=True, null=True, upload_to='partner_faktury/%Y/%m/', verbose_name='faktura PDF')),
                ('poznamka', models.CharField(blank=True, max_length=300)),
                ('odeslana_emailem', models.BooleanField(default=False)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'jednorázová faktura',
                'verbose_name_plural': 'jednorázové faktury',
                'ordering': ['-datum_vystaveni', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Vydaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(db_index=True)),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poznamka', models.CharField(max_length=300)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'výdaj',
                'verbose_name_plural': 'výdaje',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VydajSablona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=80, unique=True, verbose_name='název')),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('poznamka', models.CharField(blank=True, max_length=300)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'šablona výdaje',
                'verbose_name_plural': 'šablony výdajů',
                'ordering': ['nazev'],
            },
        ),
        migrations.AddField(
            model_name='extrafaktura',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_faktury', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='extrafaktura',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_faktury', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vydaj',
            name='salon',
            field=models.ForeignKey(blank=True, help_text='Prázdné = generic výdaj, ne k partnerovi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vydaje', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='vydaj',
            name='ucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vydaje', to='partner_admin.ulovcislouctu'),
        ),
        migrations.AddField(
            model_name='vydaj',
            name='vytvoril',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vydaje', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vydajsablona',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vydaj_sablony', to='salons.salon'),
        ),
        migrations.AddField(
            model_name='vydajsablona',
            name='ucet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vydaj_sablony', to='partner_admin.ulovcislouctu'),
        ),
    ]
