# Generated by Django 5.2 on 2026-06-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='název')),
                ('description', models.TextField(blank=True, verbose_name='popis')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='adresa')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'salon',
                'verbose_name_plural': 'salony',
            },
        ),
        migrations.CreateModel(
            name='Novinka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nadpis', models.CharField(max_length=200, verbose_name='nadpis')),
                ('text', models.TextField(verbose_name='text')),
                ('datum', models.DateField(auto_now_add=True, verbose_name='datum')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novinky', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'novinka',
                'verbose_name_plural': 'novinky',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CenikPolozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='název služby')),
                ('cena', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='cena (Kč)')),
                ('poradi', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cenik', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'položka ceníku',
                'verbose_name_plural': 'položky ceníku',
                'ordering': ['poradi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OteviraciDoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('den', models.IntegerField(choices=[(0, 'Pondělí'), (1, 'Úterý'), (2, 'Středa'), (3, 'Čtvrtek'), (4, 'Pátek'), (5, 'Sobota'), (6, 'Neděle')], verbose_name='den')),
                ('od', models.TimeField(blank=True, null=True, verbose_name='od')),
                ('do', models.TimeField(blank=True, null=True, verbose_name='do')),
                ('zavreno', models.BooleanField(default=False, verbose_name='zavřeno')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oteviraci_doba', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'otevírací doba',
                'verbose_name_plural': 'otevírací doby',
                'ordering': ['den'],
                'unique_together': {('salon', 'den')},
            },
        ),
    ]
