# Generated by Django 5.2 on 2026-06-26 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='hero_image',
            field=models.URLField(blank=True, max_length=500, verbose_name='úvodní fotka (URL)'),
        ),
        migrations.CreateModel(
            name='SalonObrazek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL obrázku')),
                ('popis', models.CharField(blank=True, max_length=200, verbose_name='popis')),
                ('poradi', models.PositiveIntegerField(default=0, verbose_name='pořadí')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obrazky', to='salons.salon', verbose_name='salon')),
            ],
            options={
                'verbose_name': 'obrázek',
                'verbose_name_plural': 'obrázky',
                'ordering': ['poradi', 'id'],
            },
        ),
    ]
