# Generated by Django 5.2 on 2026-06-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salon_hero_image_salonobrazek'),
    ]

    operations = [
        migrations.AddField(
            model_name='novinka',
            name='obrazek',
            field=models.URLField(blank=True, max_length=500, verbose_name='obrázek (URL)'),
        ),
    ]
