# Generated by Django 5.2 on 2026-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_novinka_obrazek'),
    ]

    operations = [
        migrations.AddField(
            model_name='cenikpolozka',
            name='aktivni',
            field=models.BooleanField(default=True, verbose_name='aktivní pro rezervace'),
        ),
        migrations.AddField(
            model_name='cenikpolozka',
            name='delka_minut',
            field=models.PositiveIntegerField(default=30, verbose_name='délka služby (min)'),
        ),
        migrations.AddField(
            model_name='cenikpolozka',
            name='rezerva_minut',
            field=models.PositiveIntegerField(default=0, verbose_name='časová rezerva po službě (min)'),
        ),
    ]
