"""
Django settings for salon_api project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Načtení .env souboru (pokud existuje)
_env_path = BASE_DIR / '.env'
if _env_path.exists():
    for line in _env_path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if line and not line.startswith('#') and '=' in line:
            key, _, val = line.partition('=')
            os.environ.setdefault(key.strip(), val.strip())


def _env_bool(key, default=False):
    return os.environ.get(key, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def _env_list(key, default=''):
    return [x.strip() for x in os.environ.get(key, default).split(',') if x.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# V produkci VŽDY nastavte SECRET_KEY v .env. Fallback slouží jen pro lokální vývoj.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-i-i@a&2$uh_sl&!hw41-cscn6a0%50i$0kh6&rzcd3@x269y%6',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Default je False (produkce). Pro lokální vývoj nastavte DEBUG=True v .env.
DEBUG = _env_bool('DEBUG', False)

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'salons',
    'rezervace',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'salon_api.security_middleware.SecurityHeadersMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'salon_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salon_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Produkce: nastavte DB_NAME (+ DB_USER, DB_PASSWORD, DB_HOST) v .env → PostgreSQL.
# Lokální vývoj bez těchto proměnných zůstává na SQLite.

if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ.get('DB_USER', 'ulov'),
            'PASSWORD': os.environ.get('DB_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'cs'

TIME_ZONE = 'Europe/Prague'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
# Statika (Django admin, DRF) se v produkci sbírá přes `collectstatic` do STATIC_ROOT
# a servíruje ji WhiteNoise přímo z Gunicornu. Fotky salonů jdou na Bunny.net CDN.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Lokální heslo pro administraci salonů (simulované přihlášení — odstranit v produkci)
SALON_ADMIN_PASSWORD = os.environ.get('SALON_ADMIN_PASSWORD', 'admin123')

# GDPR — jednotná retenční doba pro všechny salony (měsíce); mění pouze provozovatel platformy
GDPR_UCHOVAVANI_MESICU_DEFAULT = int(os.environ.get('GDPR_UCHOVAVANI_MESICU', '12'))

# Redis — sdílená cache (throttling) + broker pro Celery.
# Bez REDIS_URL zůstane LocMem (lokální vývoj). V Dockeru: redis://redis:6379/0
REDIS_URL = os.environ.get('REDIS_URL', '').strip()

# E-maily přes frontu (Celery). false = sync SMTP jako dřív (rollback / nouzový režim).
# Zapínejte jen když běží služba `worker` a Redis.
EMAIL_VIA_CELERY = _env_bool('EMAIL_VIA_CELERY', False)
if EMAIL_VIA_CELERY and not REDIS_URL:
    EMAIL_VIA_CELERY = False

if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
            'KEY_PREFIX': 'ulov',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'ulov-rezervaci',
        }
    }

# Celery (použije se jen při EMAIL_VIA_CELERY=true; broker může běžet i pro budoucí tasky)
CELERY_BROKER_URL = REDIS_URL or 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = None
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 120
CELERY_TASK_SOFT_TIME_LIMIT = 90
CELERY_TASK_DEFAULT_RETRY_DELAY = 60
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = os.environ.get('CELERY_TIMEZONE', 'Europe/Prague')

# CORS — API tokeny (X-Staff-Token), ne session cookies
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
else:
    CORS_ALLOW_ALL_ORIGINS = DEBUG

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-admin-password',
    'x-admin-actor',
    'x-staff-token',
]
CORS_ALLOW_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5500',
    'http://localhost:5501',
    'http://localhost:5502',
    'http://localhost:5503',
    'http://127.0.0.1:5500',
    'http://127.0.0.1:5501',
    'http://127.0.0.1:5502',
    'http://127.0.0.1:5503',
    'http://localhost:5510',
    'http://127.0.0.1:5510',
]
_extra_csrf = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
if _extra_csrf:
    CSRF_TRUSTED_ORIGINS.extend(o.strip() for o in _extra_csrf.split(',') if o.strip())

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
REFERRER_POLICY = 'strict-origin-when-cross-origin'

# Produkční HTTPS hardening — aktivní jen mimo DEBUG (za Nginx reverse proxy).
if not DEBUG:
    # Nginx terminuje TLS a předává hlavičku X-Forwarded-Proto.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = _env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'rezervace': '20/hour',
        'password_reset': '3/hour',
        'email_potvrzeni': '10/hour',
        'poptavka': '5/hour',
    },
}

# Bunny.net Storage – obrázky salonů
# Nastavte v backend/.env (viz .env.example)
BUNNY_STORAGE_ZONE = os.environ.get('BUNNY_STORAGE_ZONE', '')
BUNNY_STORAGE_API_KEY = os.environ.get('BUNNY_STORAGE_API_KEY', '')
BUNNY_STORAGE_REGION = os.environ.get('BUNNY_STORAGE_REGION', '')
BUNNY_CDN_BASE_URL = os.environ.get('BUNNY_CDN_BASE_URL', '')
BUNNY_STORAGE_PATH_PREFIX = os.environ.get('BUNNY_STORAGE_PATH_PREFIX', 'webs')

# Nahrávání obrázků — automatická komprese (delší strana max px, JPEG/WebP kvalita)
IMAGE_UPLOAD_MAX_PX = int(os.environ.get('IMAGE_UPLOAD_MAX_PX', '1920'))
IMAGE_UPLOAD_JPEG_QUALITY = int(os.environ.get('IMAGE_UPLOAD_JPEG_QUALITY', '85'))
IMAGE_UPLOAD_WEBP_QUALITY = int(os.environ.get('IMAGE_UPLOAD_WEBP_QUALITY', '85'))

# E-mail
# Bez EMAIL_HOST_PASSWORD se e-maily jen vypisují do konzole backendu (dev).
# Pro Gmail: zapněte 2FA → https://myaccount.google.com/apppasswords
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'false').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'rezervace@ulovrezervaci.cz')
POPTAVKA_EMAIL = os.environ.get('POPTAVKA_EMAIL', '')

if EMAIL_HOST_PASSWORD and EMAIL_HOST_USER:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND',
        'django.core.mail.backends.smtp.EmailBackend',
    )
else:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND',
        'django.core.mail.backends.console.EmailBackend',
    )


# Logging — pouze na stdout. Sběr řeší Docker (`docker compose logs`) + Sentry.
# Žádné logování do souborů (jednodušší provoz, žádná rotace/plnění disku).
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO').upper()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': LOG_LEVEL,
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': LOG_LEVEL,
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}


# Sentry — aktivní jen když je nastaven SENTRY_DSN (jinak žádná režie).
SENTRY_DSN = os.environ.get('SENTRY_DSN', '').strip()
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        send_default_pii=False,
    )
