# Generated by Django 5.2 on 2026-09-13 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rezervace', '0035_reset_smtp_passwords'),
        ('salons', '0008_cenikpolozka_rizikovy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivnikSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('expirace', models.DateTimeField()),
                ('zamestnanec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_sessiony', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'Archivník session',
                'verbose_name_plural': 'Archivník sessiony',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('jmeno', models.CharField(blank=True, default='', max_length=120, verbose_name='jméno')),
                ('prijmeni', models.CharField(max_length=160, verbose_name='příjmení / název')),
                ('telefon', models.CharField(blank=True, default='', max_length=40, verbose_name='telefon')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='e-mail')),
                ('adresa', models.CharField(blank=True, default='', max_length=300, verbose_name='adresa')),
                ('poznamka', models.TextField(blank=True, default='', verbose_name='interní poznámka')),
                ('stav', models.CharField(choices=[('aktivni', 'Aktivní'), ('archivovany', 'Archivovaný')], db_index=True, default='aktivni', max_length=16)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_customers', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_customers_vytvorene', to='rezervace.zamestnanec')),
                ('zmenil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_customers_zmenene', to='rezervace.zamestnanec')),
            ],
            options={
                'verbose_name': 'zákazník',
                'verbose_name_plural': 'zákazníci',
                'ordering': ['prijmeni', 'jmeno'],
            },
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('poradi', models.PositiveSmallIntegerField(default=0)),
                ('aktivni', models.BooleanField(default=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_object_types', to='salons.salon')),
            ],
            options={
                'verbose_name': 'typ objektu',
                'verbose_name_plural': 'typy objektů',
                'ordering': ['poradi', 'nazev'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(max_length=160, verbose_name='název')),
                ('popis', models.TextField(blank=True, default='', verbose_name='popis')),
                ('stav', models.CharField(choices=[('aktivni', 'Aktivní'), ('archivovany', 'Archivovaný')], db_index=True, default='aktivni', max_length=16)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_objects', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_objects_vytvorene', to='rezervace.zamestnanec')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objekty', to='archivnik.customer')),
                ('zmenil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_objects_zmenene', to='rezervace.zamestnanec')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objekty', to='archivnik.objecttype')),
            ],
            options={
                'verbose_name': 'objekt',
                'verbose_name_plural': 'objekty',
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('termin', models.DateField(verbose_name='termín')),
                ('text', models.CharField(max_length=300, verbose_name='text')),
                ('stav', models.CharField(choices=[('aktivni', 'Aktivní'), ('hotovo', 'Hotovo')], db_index=True, default='aktivni', max_length=16)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pripominky', to='archivnik.object')),
                ('prirazeny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_pripominky', to='rezervace.zamestnanec')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_reminders', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_reminders_vytvorene', to='rezervace.zamestnanec')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pripominky', to='archivnik.customer')),
            ],
            options={
                'verbose_name': 'připomínka',
                'verbose_name_plural': 'připomínky',
                'ordering': ['termin', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('rozsah', models.CharField(choices=[('zakaznik', 'Zákazník'), ('objekt', 'Objekt'), ('obe', 'Zákazník i objekt')], default='obe', max_length=16)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_tags', to='salons.salon')),
            ],
            options={
                'verbose_name': 'štítek',
                'verbose_name_plural': 'štítky',
                'ordering': ['nazev'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='tagy',
            field=models.ManyToManyField(blank=True, related_name='objekty', to='archivnik.tag'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tagy',
            field=models.ManyToManyField(blank=True, related_name='zakaznici', to='archivnik.tag'),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nastalo', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datum a čas zápisu')),
                ('typ_zapisu', models.CharField(default='Poznámka', max_length=80, verbose_name='typ zápisu')),
                ('nadpis', models.CharField(blank=True, default='', max_length=200, verbose_name='nadpis')),
                ('text', models.TextField(verbose_name='text')),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('upraveno', models.DateTimeField(auto_now=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_entries', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_entries_vytvorene', to='rezervace.zamestnanec')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zapisy', to='archivnik.customer')),
                ('zmenil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_entries_zmenene', to='rezervace.zamestnanec')),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zapisy', to='archivnik.object')),
            ],
            options={
                'verbose_name': 'zápis',
                'verbose_name_plural': 'zápisy',
                'ordering': ['-nastalo', '-vytvoreno'],
                'indexes': [models.Index(fields=['salon', '-nastalo'], name='archivnik_e_salon_i_4cfeba_idx'), models.Index(fields=['zakaznik', '-nastalo'], name='archivnik_e_zakazni_f62b19_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='objecttype',
            constraint=models.UniqueConstraint(fields=('salon', 'nazev'), name='archivnik_objecttype_salon_nazev'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('salon', 'nazev'), name='archivnik_tag_salon_nazev'),
        ),
        migrations.AddIndex(
            model_name='object',
            index=models.Index(fields=['salon', 'nazev'], name='archivnik_o_salon_i_ec43e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='object',
            constraint=models.UniqueConstraint(fields=('id', 'zakaznik'), name='archivnik_object_id_zakaznik'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['salon', 'prijmeni', 'jmeno'], name='archivnik_c_salon_i_1bbbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['salon', 'telefon'], name='archivnik_c_salon_i_d79e82_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('salon', 'email'), name='archivnik_customer_salon_email'),
        ),
    ]
