# Generated by Django 5.2 on 2026-09-13 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivnik', '0001_initial'),
        ('rezervace', '0035_reset_smtp_passwords'),
        ('salons', '0008_cenikpolozka_rizikovy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(max_length=80, verbose_name='název')),
                ('druh', models.CharField(choices=[('text', 'Text'), ('cislo', 'Číslo'), ('datum', 'Datum'), ('ano_ne', 'Ano / ne')], default='text', max_length=16)),
                ('poradi', models.PositiveSmallIntegerField(default=0)),
                ('aktivni', models.BooleanField(default=True)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_field_defs', to='salons.salon')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pole', to='archivnik.objecttype')),
            ],
            options={
                'verbose_name': 'vlastní pole',
                'verbose_name_plural': 'vlastní pole',
                'ordering': ['poradi', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.CharField(blank=True, default='', max_length=300)),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoty_poli', to='archivnik.object')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hodnoty', to='archivnik.customfielddef')),
            ],
            options={
                'verbose_name': 'hodnota vlastního pole',
                'verbose_name_plural': 'hodnoty vlastních polí',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('druh', models.CharField(choices=[('fotografie', 'Fotografie'), ('dokument', 'Dokument')], default='dokument', max_length=16)),
                ('nazev', models.CharField(max_length=200, verbose_name='název')),
                ('content_type', models.CharField(max_length=80)),
                ('velikost', models.PositiveIntegerField(default=0)),
                ('storage_key', models.CharField(max_length=400)),
                ('vytvoreno', models.DateTimeField(auto_now_add=True)),
                ('objekt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soubory', to='archivnik.object')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivnik_assets', to='salons.salon')),
                ('vytvoril', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivnik_assets_vytvorene', to='rezervace.zamestnanec')),
                ('zakaznik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soubory', to='archivnik.customer')),
                ('zapis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prilohy', to='archivnik.entry')),
            ],
            options={
                'verbose_name': 'soubor',
                'verbose_name_plural': 'soubory',
                'ordering': ['-vytvoreno'],
                'indexes': [models.Index(fields=['salon', 'zakaznik'], name='archivnik_a_salon_i_4f1eb0_idx'), models.Index(fields=['objekt', 'druh'], name='archivnik_a_objekt__9c2939_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customfielddef',
            constraint=models.UniqueConstraint(fields=('typ', 'nazev'), name='archivnik_fielddef_typ_nazev'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(fields=('objekt', 'pole'), name='archivnik_fieldvalue_objekt_pole'),
        ),
    ]
