# Generated by Django 5.2 on 2026-09-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivnik', '0002_custom_fields_and_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='archivnik.asset', verbose_name='hlavní fotografie'),
        ),
    ]
